version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bodega_cats
      POSTGRES_USER: bodega_user
      POSTGRES_PASSWORD: bodega_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bodega-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://bodega_user:bodega_password@db:5432/bodega_cats
      - JWT_SECRET_KEY=your-secret-key-here
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - bodega-network
    command: flask run --host=0.0.0.0

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - REACT_APP_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - bodega-network
    command: npm start

volumes:
  postgres_data:

networks:
  bodega-network:
    driver: bridge 