services:
  - type: web
    name: bodega-cat-finder-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        fromDatabase:
          name: bodega-cats-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PASSWORD_SALT
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false

databases:
  - name: bodega-cats-db
    databaseName: bodega_cats
    user: bodega_user 